services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - "5452:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data

    hublast_hub_backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: always
        ports:
            - "5000:5000"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            DB_HOST: db
            DB_PORT: 5432
        depends_on:
            - db

    hublast_hub_frontend:
        build:
            context: ./frontend/hublast
            dockerfile: Dockerfile
        restart: always
        ports:
            - "3000:3000"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            DB_HOST: db
            DB_PORT: 5432
        depends_on:
            - db

volumes:
    db_data:
